"""Initial migration: create users and projects tables

Revision ID: 9c349149936d
Revises: 
Create Date: 2025-09-24 05:08:00.953425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c349149936d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('client', sa.String(), nullable=False),
    sa.Column('orderValue', sa.String(), nullable=True),
    sa.Column('proposal', sa.String(), nullable=True),
    sa.Column('pct', sa.String(), nullable=True),
    sa.Column('phase', sa.Enum('INCEPTION', 'DEFINITION', 'BUILT', 'DEPLOY', 'CLOSE', name='projectphase'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'HOLD', 'COMPLETED', 'CANCELLED', name='projectstatus'), nullable=False),
    sa.Column('startDate', sa.Date(), nullable=False),
    sa.Column('estimatedEndDate', sa.Date(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', 'MEMBER', name='userrole'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('projects')
    # Drop ENUMs manually
    op.execute('DROP TYPE IF EXISTS projectphase')
    op.execute('DROP TYPE IF EXISTS projectstatus')
    op.execute('DROP TYPE IF EXISTS userrole')
    # ### end Alembic commands ###
